config/routes.rb
Rails.application.routes.draw do
  root to: 'members#index'
  resources :members, only: [:index, :show, :edit, :update, :destroy]
  resources :member_registrations, only: [:new, :create]
#  post 'member_registrations', to: 'member_registrations#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :member_positions, dependent: :destroy
  has_many :positions, through: :member_positions
  accepts_nested_attributes_for :member_positions, allow_destroy: true
end

app/models/member_position.rb
class MemberPosition < ApplicationRecord
  belongs_to :member
  belongs_to :position
end

app/models/member_registration.rb
class MemberRegistration
  include ActiveModel::Model

  attr_accessor :name, :position, :introduction
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :member_positions, dependent: :destroy
  has_many :members, through: :member_positions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/member_registrations_controller.rb
class MemberRegistrationsController < ApplicationController
  before_action :set_position, only: :new

  def new
    @member_registration = MemberRegistration.new
  end

  def create
    # serviceを呼び出す
    # validation等は今回は考慮しない
    registrationCreateService = RegistrationCreateService.new(member_registration_params)
    registrationCreateService.execute
    redirect_to members_path
  end

  private
  def set_position
    @positions = Position.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def member_registration_params
    params.require(:member_registration).permit(:name, :introduction, position:[])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/1/edit
  def edit
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tmp20181109</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/member_registrations/new.html.erb
<h1>New Member</h1>

<%= form_with(model: @member_registration, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.collection_check_boxes :position, @positions, :id, :name, include_hidden: false do |ccb| %>
      <%= ccb.label { ccb.check_box + ccb.text } %>
    <% end %>
  </div>


  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', members_path %>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :introduction %>
    <%= form.text_area :introduction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Introduction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.introduction %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_registration_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Introduction:</strong>
  <%= @member.introduction %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>